site_name: DSMRloggerWS
site_url: https://willem.aandewiel.nl/index.php/2018/08/28/slimme-meter-uitlezer/
site_description: Project documentation with Markdown.
site_author: Willem Aandewiel
copyright: 'copyright &copy; 2019 <a href="https://willem.aandewiel.nl/index.php/2019/04/09/dsmr-logger-v4-slimme-meter-uitlezer/">Willem Aandewiel</a>'

extra:
    version: 1.0.4

extra_css: 
    - extra.css

theme:
    name: readthedocs
    custom_dir: custom_theme/
    prev_next_buttons_location: top
    config.theme.titles_only: true
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - c++

plugins:
    - search
    - git-revision-date

nav:
    - 'index.md'
    - 'introductie.md'

    - Voorbereiding:
       - 'ArduinoIDE': 'installatieArduinoIDE.md'
       - 'ESP8266 Core': 'installatieESP8266core.md'
       - 'Data Upload Tool': 'installatieDataUploadTool.md'
       - 'Installeren Bibliotheken': 'installatieBibliotheken.md'

    - Firmware:
       - 'Benodigd Bibliotheken': 'benodigdeBibliotheken.md'
       - 'DSMRloggerWS firmware': 'clonenFirmware.md'
       - 'Firmware Flashen DSMR-logger v4': 'uploadFirmware_V4.md'
       - 'Data Flashen DSMR-logger v4': 'uploadDataMap_V4.md'
       - 'Firmware Flashen DSMR-logger v3': 'uploadFirmware_V3.md'
       - 'Data Flashen DSMR-logger v3': 'uploadDataMap_V3.md'

    - 'Selectie Functies':
          - 'Overzicht': 'overzichtFuncties.md'
          - 'DSMR-logger V4 met ESP-12': 'Is_ESP12.md'
          - 'Over The Air update': 'Use_Update_Server.md'
          - '0.96" OLED display': 'Has_OLED_SSD1306.md'
          - '1.3" OLED display': 'Has_OLED_SH1106.md'
          - 'Gebruik MQTT': 'Use_MQTT.md'
          - 'Gebruik mindergas.nl': 'Use_Mindergas.md'
          - 'Pr√© DSMR 4.0 Slimme Meters': 'Use_Pre40_Protocol.md'
          - 'Network Time': 'Use_NTP_Time.md'
          - 'SM geeft geen info per Fase': 'SM_Has_No_Fase_Info.md'
          - 'Toon wachtwoorden': 'Show_Passwrds.md'
          - 'Test mode': 'Has_No_Meter.md'

    - Hardware:
       - 'DSMR-logger v4': 'hardware_V4.md'
       - 'Programmer DSMR-logger v4': 'hardware_V4_Programmer.md'
       - 'DSMR-logger v3': 'hardware_V3.md'
       - 'Programmer DSMR-logger v3': 'hardware_V3_Programmer.md'

    - Overigen:
       - (eerste keer) Opstarten: 'Opstarten.md'
       - restAPI: 'restAPI.md'
       - Verschillen ESP8266 modules: 'verschillenESP8266.md'
       - PUYA chips: 'PUYA_patch.md'
       - Vragen en Antwoorden: 'QenA.md'

    - Intergratie met andere systemen:
       - Integratie Domoticz: 'integratieDomoticz.md'
       - Integratie Homey: 'integratieHomey.md'
       - Integratie Home Assistant: 'integratieHassio.md'
       - Integratie Mindergas.nl: 'integratieMindergas.md'

    - telnet:
       - logging output: 'telnet.md'

    - License: 'MITlicense.md'

